package view.gui;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.io.FileWriter;
import java.io.IOException;
import model.validations.UserDataValidations;
import ficheros.ClassFichero;
import java.io.FileNotFoundException;
import Exceptions.InvalidNameException;
import Exceptions.InvalidEmailException;

/**
 *
 * @author danielgarbru
 */

public class JFrameMain extends javax.swing.JFrame {

    /**
     * Creates new form JFrameMain
     */
    public JFrameMain() {
        initComponents();
        initConfig();
    }

    private void initConfig() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        // Auto-generated initialization code - not modified
    }// </editor-fold>//GEN-END:initComponents

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
        // TODO add your handling code here:
        String name = jTextFieldName.getText();
        String nif = jTextFieldNIF.getText();
        String email = jTextFieldEmail.getText();
        String date = jTextFieldBirthDate.getText();
        String zip = jTextFieldZIP.getText();
        boolean isValid = true; // Variable para verificar si todo está correcto

        try {
            UserDataValidations.checkName(name); // Ahora este método lanza InvalidNameException
            jLabelError.setText("");
            jTextFieldName.setEditable(false);
        } catch (InvalidNameException e) {
            jLabelError.setText(e.getMessage());
            isValid = false;
        }

        // Check NIF (ID)
        if (!UserDataValidations.checkId(1, nif)) {
            ErrorNIF.setText("NIF incorrecto");
            isValid = false;
        } else {
            ErrorNIF.setText("");
            jTextFieldNIF.setEditable(false);
        }

        // Check Email
        try {
            UserDataValidations.checkEmail(email);
            ErrorEmail.setText("");
            jTextFieldEmail.setEditable(false);
        } catch (InvalidEmailException e) {
            ErrorEmail.setText(e.getMessage());
            isValid = false;
        }

        // Check Date
        if (!UserDataValidations.checkFormatDate(date)) {
            ErrorCumple.setText("Fecha incorrecta");
            isValid = false;
        } else {
            int edad = UserDataValidations.calculateAge(date);
            jTextFieldAge.setText(String.valueOf(edad));
            jTextFieldBirthDate.setEditable(false);
        }

        // Check ZIP code
        if (!UserDataValidations.checkPostalCode(zip)) {
            ErrorZip.setText("Código postal incorrecto");
            isValid = false;
        } else {
            ErrorZip.setText("");
            jTextFieldZIP.setEditable(false);
        }

        if (isValid) {
            System.out.println("Todos los datos son correctos.");
        }
    }//GEN-LAST:event_Button1ActionPerformed

    private void jButtonCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCleanActionPerformed
        // TODO add your handling code here:
        jTextFieldName.setEditable(true);
        jTextFieldName.setText("");
        jTextFieldNIF.setEditable(true);
        jTextFieldNIF.setText("");
        jTextFieldEmail.setEditable(true);
        jTextFieldEmail.setText("");
        jTextFieldBirthDate.setEditable(true);
        jTextFieldBirthDate.setText("");
        jTextFieldZIP.setEditable(true);
        jTextFieldZIP.setText("");
        jTextFieldAge.setText("");
        jLabelError.setText("");
        ErrorNIF.setText("");
        ErrorEmail.setText("");
        ErrorCumple.setText("");
        ErrorZip.setText("");

    }//GEN-LAST:event_jButtonCleanActionPerformed

    private void jTextFieldAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAgeActionPerformed

    private void jButtonCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCSVActionPerformed
        String name = jTextFieldName.getText();
        String nif = jTextFieldNIF.getText();
        String email = jTextFieldEmail.getText();
        String date = jTextFieldBirthDate.getText();
        String zip = jTextFieldZIP.getText();
        String age = jTextFieldAge.getText();
        String line = name + ";" + nif + ";" + email + ";" + date + ";" + zip + ";" + age + ";";

        ClassFichero.writeFile(line);
    }//GEN-LAST:event_jButtonCSVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws FileNotFoundException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMain().setVisible(true);
            }
        });
        ClassFichero.createFile("user_data_DGB.csv");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Button1;
    private javax.swing.JLabel ErrorCumple;
    private javax.swing.JLabel ErrorEdad;
    private javax.swing.JLabel ErrorEmail;
    private javax.swing.JLabel ErrorNIF;
    private javax.swing.JLabel ErrorZip;
    private javax.swing.JButton jButtonCSV;
    private javax.swing.JButton jButtonClean;
    private javax.swing.JLabel jLabel1Age;
    private javax.swing.JLabel jLabel1BirthDate;
    private javax.swing.JLabel jLabel1Email;
    private javax.swing.JLabel jLabel1NIF;
    private javax.swing.JLabel jLabel1Name;
    private javax.swing.JLabel jLabel1ZIP;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JTextField jTextFieldAge;
    private javax.swing.JTextField jTextFieldBirthDate;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNIF;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldZIP;
    // End of variables declaration//GEN-END:variables
}